#!/usr/bin/env bash

# inspired by elementary-template setup.sh script by ChildishGiant:
# https://github.com/watsonprojects/elementary-template/blob/main/setup.sh

# Get app name
read -rp "Enter app name with intended capitalisation: " app_title
app_name=$(echo "${app_title}" | tr '[:upper:]' '[:lower:]')
app_name=${app_name// /-}

# Get user name
read -rp "Enter github username: " user_name
user_name=$(echo "${user_name}" | tr '[:upper:]' '[:lower:]')

# Set App ID and path
app_id="io.github.${user_name}.${app_name}"
app_path="${app_id//./\/}"

# Get App Namespace
read -rp "Enter namespace to use for the application (Used in Vala code files): " app_namespace

# Get App summary
read -rp "Enter app summary (will be used in desktop file and AppStream metainfo): " app_summary

# Get App categories
read -rp "Enter app categories (semi-colon-seperated) e.g \"Office;Network;\": " app_categories

# Get App Keywords
read -rp "Enter app keywords (so that you app is more discoverable in app stores): " app_keywords

# Get App Homepage URL
read -rp "Enter app homepage URL: " app_homepage_url

# Get App Bug Tracker URL
read -rp "Enter app bug tracker URL: " app_bug_tracker_url

# Get App License Type
read -rp "Enter app license type: " app_license_type

# Replace all instances of app_title in files
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_TITLE}}/${app_title}/g" {} +

# Replace all instances of app_name in files
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_NAME}}/${app_name}/g" {} +

# Replace all instances of user_name in files
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{USER_NAME}}/${user_name}/g" {} +

# Replace all instances of app_id in files
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_ID}}/${app_id}/g" {} +

# Replace all instances of app_namespace in files
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_NAMESPACE}}/${app_namespace}/g" {} +

# Replace all instances of app_path in files
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_PATH}}/${app_path}/g" {} +

# Replace all instances of app_summary
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_SUMMARY}}/${app_summary}/g" {} +

# Replace all instances of app_categories
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_CATEGORIES}}/${app_categories}/g" {} +

# Replace all instances of app_keywords
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_KEYWORDS}}/${app_keywords}/g" {} +

# Replace all instances of app_homepage_url
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_HOMEPAGE_URL}}/${app_homepage_url}/g" {} +

# Replace all instances of app_bug_tracker_url
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_BUG_TRACKER_URL}}/${app_bug_tracker_url}/g" {} +

# Replace all instances of app_license_type
find . -type f -not -path '*/\.*' -not -name "setup.sh" -exec sed -i "s/{{APP_LICENSE_TYPE}}/${app_license_type}/g" {} +

# Rename all template named data and metadata files
mv "data/{{APP_NAME}}-build.gresource.xml.in" "data/${app_name}-build.gresource.xml.in"
mv "data/{{APP_NAME}}.desktop.in.in" "data/${app_name}.desktop.in.in"
mv "data/{{APP_NAME}}.gresource.xml.in" "data/${app_name}.gresource.xml.in"
mv "data/{{APP_NAME}}.gschema.xml.in" "data/${app_name}.gschema.xml.in"
mv "data/{{APP_NAME}}.metainfo.xml.in.in" "data/${app_name}.metainfo.xml.in.in"
mv "{{APP_ID}}.json" "${app_id}.json"
